name: Automate Weather Data

on:
  # Scheduling the workflow to run daily at 10 AM UTC
  schedule:
    - cron: '0 10 * * *'

  # Allowing manual triggering of the workflow
  workflow_dispatch:

jobs:
  update-weather-data:
    # Using an Ubuntu-based virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checking out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        # Step 2: Running the weather.sh script
      - name: Run Weather Script
        run: |
         chmod +x weather.sh 
         ./weather.sh 
        # Step 3: Committing and pushing changes back to the repository
      - name: Commit and Push Changes
        run: |
         git config --global user.name "vinnycascone"
         git config --global user.email "v.cascone92@gmail.com"
         git add .
         git commit -m "Update weather data [automated]"
         git push
        env:
        # adding GitHub token for authentication
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 